<div class="box ">
	<?php if(user_has_permission('can-start-livestream')): ?>
		<div class="box-content">
			<a onclick="loadLivestreamFrame(0)" href="#!" class="btn btn-block btn-secondary"><i class="ion-ios-plus-empty"></i> <?php echo lang('livestreaming::start-new-livestream') ?>
			</a>
		</div>
	<?php endif ?>
	<ul class="menu">
		<?php foreach(get_menus("livestreams-menu") as $menu): ?>
			<li>
				<a href="<?php echo $menu->link ?>"><?php echo lang($menu->title) ?></a>
			</li>
		<?php endforeach ?>
		<li>
			<a href="<?php echo url('livestreams?type=mine') ?>"><?php echo lang('livestreaming::my-livestreams') ?></a>
		</li>
		<li>
			<a href="<?php echo url('livestreams') ?>"><?php echo lang('livestreaming::all-livestreams') ?></a>
		</li>
	</ul>
</div>