<?php $livestreams = get_livestreams('user-profile', 'all', null, app()->profileUser['id'], $limit); ?>
<?php if($livestreams->total): ?>
	<div class="box">
		<div class="title"><?php echo lang('livestream::recent-livestreams') ?></div>
		<div class="box-content" id="livestream-widget">
			<?php foreach($livestreams->results() as $livestream): ?>
				<div class="media media-lg user">
					<div class="media-left">
						<a ajax="true" href="<?php echo get_livestream_url($livestream) ?>">
							<div class="media-object" style="background-image: url(<?php echo $livestream['preview_path'] ? url_img($livestream['preview_path'], 75) : img('livestream::images/preview.png', 75) ?>); background-position: center; background-size: cover;"></div>
						</a>
					</div>
					<div class="media-body">
						<a ajax="true" href="<?php echo get_livestream_url($livestream) ?>">
							<h6 class="media-heading" style="font-weight: normal"><?php echo ($livestream['title']) ? $livestream['title'] : lang('livestream::untitled-livestream') ?></h6>
						</a>
						<p class="help-block"><?php echo str_limit($livestream['description'], 100) ?></p>
					</div>
				</div>
			<?php endforeach ?>
		</div>
	</div>
<?php endif ?>