<div class="box">
	<div class="title"><?php echo lang("livestreaming::livestreams") ?></div>
	<div class="box-content">
		<?php foreach($livestreams->results() as $livestream): ?>
			<?php echo view('livestream::livestream', array('livestream' => $livestream)) ?>
		<?php endforeach ?>
	</div>
	<?php if($livestreams->total): ?>
		<div class="box-content">
			<?php echo $livestreams->append(array('category' => input('category'), 'term' => input('term'), 'type' => 'user-profile'))->links(); ?>
		</div>
	<?php else: ?>
		<div class="box-content">
			<div class="alert alert-info"><?php echo lang('livestream::no-livestreams-found-here') ?></div>
		</div>
	<?php endif ?>
</div>