<?php
$slug = $notification['type_id'];
$user = get_user($notification['from_userid']);
?>
<div id="notification-<?php echo $notification['notification_id']?>" class="notification media media-md  <?php echo ($notification['mark_read'] == 0) ? 'notification-unread' : null?>">
    <div class="media-left">
        <div class="media-object"><a onclick="loadLivestreamFrame(<?php echo $slug; ?>)" href="#!"><img src="<?php echo get_livestream_preview($slug); ?>"/></a> </div></div>
    <div class="media-body">
        <a onclick="loadLivestreamFrame(<?php echo $slug; ?>)" href="#!">
            <h6 class="media-heading">
                <?php  echo $user['first_name']." ".$user['last_name'].' '; ?>
                <?php _lang('livestreaming::livestream-end')?>
            </h6>
        </a>
        <span class="timeago " title="<?php echo date('c', $notification['time'])?>"><?php echo date('c', $notification['time'])?></span>
        <div class="actions">
            <a
                class="mark-button"
                data-status="<?php echo $notification['mark_read']?>"
                data-read="<?php echo lang('notification::read')?>"
                data-mark="<?php echo lang('notification::mark-as-read')?>"
                title="<?php echo ($notification['mark_read'] == 1) ? lang('notification::read') : lang('notification::mark-as-read')?> "
                onclick="return process_notification_mark('<?php echo $notification['notification_id']?>')"
                href="#!" ><i class="ion-checkmark-circled"></i></a>
            <a onclick="return delete_notification('<?php echo $notification['notification_id']?>')" href="#!"><i class="ion-close"></i></a>
        </div>
    </div>
</div>
