<div class="box">
    <div class="box-content" style="padding: 20px 10%">
        <?php if($message):?>
            <div class="alert alert-danger"><?php echo $message?></div>
        <?php endif?>
        <?php
            $current = (config('livestream-upload', false) and config('livestream-encoder', 'none') != 'none') ? 'upload' : 'external';
        ?>
        <form action="" method="post" enctype="multipart/form-data">
            <?php CSRFProtection::embed() ?>
            <input type="hidden" name="val[entity_type]" value="<?php echo input('type', 'user')?>"/>
            <input type="hidden" name="val[entity_id]" value="<?php echo input('id', get_userid())?>"/>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('livestream::source')?></label>
                <div class="col-sm-8">
                    <select onchange="return change_livestream_source(this)" name="val[source]" class="c-select">
                        <?php if(config('livestream-upload', false)):?>
                            <option <?php echo ($current == 'upload') ? 'selected' : null?> value="upload"><?php _lang('livestream::upload-from-computer')?></option>
                        <?php endif?>
                        <option <?php echo ($current == 'external') ? 'selected' : null?> value="external"><?php _lang('livestream::external-link')?></option>
                    </select>

                    <div class="livestream-source-selector" style="margin-top: 20px">
                        <?php if(config('livestream-upload', false)):?>
                            <div class=" source upload <?php echo ($current == 'external') ? 'livestream-hide-field' : null?>" >
                                <input type="file" id="file" name="livestream_file">
                            </div>
                        <?php endif?>
                        <div class="source external <?php echo ($current == 'upload') ? 'livestream-hide-field' : null?>">
                            <div class="form-group ">
                                <input value="<?php echo input('val.link')?>" name="val[link]" type="text" class="form-control">
                                <span class="help-block"><?php _lang('livestream::external-url-info')?></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('category')?></label>
                <div class="col-sm-8">
                    <select name="val[category_id]" class=" c-select" >
                        <?php foreach(get_livestream_categories() as $category):?>
                            <?php $subCategories = get_livestream_parent_categories($category['id'])?>
                            <?php if($subCategories):?>
                                <optgroup label="<?php _lang($category['title'])?>">

                                    <?php foreach($subCategories as $cat):?>
                                        <option value="<?php echo $cat['id']?>"><?php _lang($cat['title'])?></option>
                                    <?php endforeach?>
                                </optgroup>
                            <?php else:?>
                                <option value="<?php echo $category['id']?>"><?php _lang($category['title'])?></option>
                            <?php endif?>
                        <?php endforeach?>
                    </select>
                </div>
            </div>

            <div class="livestream-details-container <?php echo ($current == 'external') ? "livestream-hide-field" : null?>" >
                <div class="form-group row">
                    <label class="control-label col-sm-4"><?php _lang('livestream::title')?></label>
                    <div class="col-sm-8">
                        <input value="<?php echo input('val.title')?>" type="text" name="val[title]" class="form-control"/>
                    </div>
                </div>



                <div class="form-group row">
                    <label class="control-label col-sm-4"><?php _lang('livestream::description')?></label>
                    <div class="col-sm-8">
                        <textarea name="val[description]" class="form-control auto-grow-input"><?php echo input('val.description')?></textarea>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php echo lang('privacy') ?></label>
                <div class="col-sm-8">
                    <?php fire_hook("system.privacy"); ?>
                </div>
            </div>
            <button class="btn btn-info"><?php _lang('livestream::add-livestream')?></button>
        </form>
    </div>
</div>