<iframe class="" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" style="border: none;padding: 0 !important;border-radius: 3px;overflow: hidden;width: 100%;" src="<?php echo url_to_pager("play-video").'?link='.$livestream['file_path']?>&height=430" width="100%" height="450"></iframe>
<?php //if(livestream_ended($livestream['id'])): ?>
<!-- <iframe src='<?php echo url('livestream/live?from_feed=1&id='.$livestream['id']); ?>' class="livestream_frame"></iframe> --!>
<?php //else: ?>
<!-- <iframe class="" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" style="border: none;padding: 0 !important;border-radius: 3px;overflow: hidden;width: 100%;" src="<?php echo url_to_pager("play-video").'?link='.$livestream['file_path']?>&height=430" width="100%" height="450"></iframe> --!>
<?php //endif ?>