<?php
$refId = $livestream['id'];
$refName = 'livestream';

?>
<div class="box">
    <div class="title" style="min-height: 45px">
    <?php echo $livestream['title']?>
    <div class="action">
        <?php if(is_livestream_owner($livestream)):?>
        <a ajax="true" href="<?php echo url('livestream/edit?id='.$livestream['id'])?>" class="btn btn-success btn-sm "><?php _lang('edit')?></a>
        <a href="<?php echo url('livestream/delete?id='.$livestream['id'])?>" class="btn btn-danger confirm btn-sm"><?php _lang('livestreaming::delete-livestream')?></a>
        <?php elseif(is_loggedIn() and plugin_loaded('report')): ?>
        <a data-type="group" data-link="<?php echo url_to_pager('livestream-page', array('id' => $livestream['slug'])) ?>" class="report-btn btn btn-secondary" href=""><i class="ion-flag"></i></a>
        <?php endif?>
    </div>
        </div>
    <div class="box-content livestream-player-container">
               <?php if($livestream['status'] == 0):?>
                    <div class="livestream-in-processing">
                        <?php _lang('livestreaming::livestream-in-processing')?>
                    </div>
                <?php else:?>
                <iframe class="" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" style="border: none;padding: 0 !important;margin:0 10px;border-radius: 3px;overflow: hidden;width: 96%;" src="<?php echo url_to_pager("play-video").'?link='.$livestream['file_path']?>&height=430" width="100%" height="450"></iframe>
                <?php endif?>
        <?php echo fire_hook('livestreamauthor.name', null, array($livestream));?>
        </div>
    <?php if(plugin_loaded('like') and config('feed-like-type', 'regular') != 'regular'):?>
        <div class="reactors reactors-<?php echo $refName?>-<?php echo $refId?>">
            <?php echo view('like::reacts', array('type' => $refName, 'type_id' => $refId))?>
        </div>
    <?php endif?>
    <div class="feed-footer">
        <ul class=" feed-footer-menu clearfix">


            <?php if(plugin_loaded('like')):?>
                <?php load_functions('like::like');?>
               				<?php echo view('like::like-footer', array('type' => $refName, 'typeId' => $refId)); ?>
            <?php endif?>
                <li><a href=""><i class="ion-ios-eye"></i> <?php echo $livestream['view_count']?> <?php _lang('livestreaming::views')?></a> </li>
                <li class="livestream-social-share-link"><?php if($livestream['privacy'] == 1 && plugin_loaded('sharer')) echo view('sharer::share_link', array('link' => url("livestream/".$livestream['slug']))) ?></li>

            <li class="pull-right">
                <ul class="feed-statistics">
                    <?php if(plugin_loaded('like') and config('feed-like-type', 'regular') == 'regular'):?>
                        <?php if(plugin_loaded('like')):?>
                            <li><a onclick="return show_likes('<?php echo $refName?>', '<?php echo $refId?>')" href=""> <i class="ion-thumbsup"></i> <span class="like-count-<?php echo $refName?>-<?php echo $refId?>"><?php echo count_likes($refName, $refId)?></span></a></li>
                            <?php if (config('enable-dislike', false)):?>
                                <li><a onclick="return show_dislikes('<?php echo $refName?>', '<?php echo $refId?>')" href=""> <i class="ion-thumbsdown"></i> <span class="dislike-count-<?php echo $refName?>-<?php echo $refId?>"><?php echo count_dislikes($refName, $refId)?></span></a></li>
                            <?php endif?>

                        <?php endif?>
                    <?php endif?>

                    <?php if(plugin_loaded('comment')):?>
                        <?php load_functions('comment::comment')?>
                        <?php $countComments = count_comments($refName, $refId);?>
                        <li> <i class="ion-chatbubbles"></i> <span class="comment-count-<?php echo $refName?>-<?php echo $refId?>"><?php echo ($countComments) ? $countComments : null?></span></li>
                    <?php endif?>

                </ul>
            </li>
        </ul>
    </div>
</div>

<div class="box">
    <div class="box-content feed-footer">
        <?php if(plugin_loaded('comment')):?>
            <div class="feed-comment-container">

                <?php if($countComments > config('feed-comment-limit', 3)):?>
                    <a id="comment-view-more-button-<?php echo $refName?>-<?php echo $refId?>" class="comment-view-more-button comment-view-more-button-<?php echo $refName?>-<?php echo $refId?>" onclick="return show_more_comment('<?php echo $refName?>', '<?php echo $refId?>', 'comment-view-more-indicator-<?php echo $refId?>')"  href=""><?php _lang('view-previous-comments')?></a>
                    <img class="comment-view-more-indicator" id="comment-view-more-indicator-<?php echo $refId?>" src="<?php echo img('images/loading.gif')?>" />
                <?php endif?>
                <div data-offset="<?php echo config('feed-comment-limit', 3)?>" data-limit="<?php echo config('feed-comment-limit', 3)?>" class="comment-lists comment-lists-<?php echo $refName?>-<?php echo $refId?>" id="">
                    <?php foreach(get_comments($refName, $refId, config('feed-comment-limit', 3), 0) as $comment):?>
                        <?php echo view('comment::display', array('comment' => $comment))?>
                    <?php endforeach;?>
                </div>
                <?php echo view('comment::editor', array(
                    'typeId' => $livestream['id'],
                    'type' => 'livestream',
                    'textLimit' => (config('enable-feed-text-limit', false)) ? config('maximum-feed-text-limit', 150) : false))?>

            </div>
        <?php endif?>
    </div>
</div>